### PR TITLE
support PE, puppet4, AIO puppet

### PR DESCRIPTION
**Pull request by jlambert121**

### CODE REVIEW

**Comment by jamtur01** [comment]
LGTM

**Comment by electrical** [comment]
thank you for this, and sorry for the delay.
I didn't receive updates on the project so didn't look at it for a long time.

**Comment by jlambert121** [comment]
No worries.  Any chance you'd publish a new ver?

**Comment by electrical** [comment]
I'll be making some more changes and will do a release soon under the elasticsearch forge handle as well.

**Comment by electrical** [comment]
will most likely be tomorrow or early next week.

**Pull request merged**
